"""Generate ``src/cmi_frameworks.py`` from the CMI Domains workbooks.

# change for b2c questionarie

The RAR (`Survey Inputs _CMI Domains.rar`) is the authority for two things the
pipeline previously invented for itself:

1. the four survey categories a B2C study must use, which differ by domain — a
   food market opens on "Consumption, Usage & Occasion Behavior" while a
   smartwatch opens on "Device Ownership & Usage";
2. the sub-sector taxonomy (1,026 rows) with its Top-5 attributes per category,
   which give the question architect real seed topics.

Run this once after the RAR is extracted; the output is a plain Python literal
so the runtime never needs openpyxl or the .xlsx files.

Usage:
    python scripts/build_cmi_frameworks.py <path-to-extracted-rar-dir>
"""
from __future__ import annotations

import glob
import os
import pprint
import sys
from pathlib import Path

import openpyxl

# The four canonical section ids the pipeline already uses, in arc order. Every
# framework in the RAR maps 1:1 onto these — usage → purchase → experience →
# future intent — which is what makes the swap safe.
CANONICAL_IDS = (
    "consumer_profile",
    "buying_behavior",
    "preferences_expectations",
    "satisfaction_future_intent",
)


def _split_attrs(cell) -> list[str]:
    """"a; b; c" -> ["a", "b", "c"]."""
    if not cell:
        return []
    return [p.strip() for p in str(cell).split(";") if p.strip()]


def build(src_dir: str) -> tuple[list[dict], list[dict]]:
    frameworks: list[dict] = []
    subsectors: list[dict] = []

    for path in sorted(glob.glob(os.path.join(src_dir, "*.xlsx"))):
        wb = openpyxl.load_workbook(path, read_only=True)
        domain_file = Path(path).stem.replace("CMI_", "").replace(
            "_Subsector_Survey_Mapping", ""
        ).replace("_Subsegment_Survey_Mapping", "").replace("_", " ")

        # --- Sheet 2: the Framework Guide (section names per classification) ---
        for sheet in wb.sheetnames:
            low = sheet.lower()
            if "framework" not in low and "guide" not in low:
                continue
            for row in wb[sheet].iter_rows(values_only=True):
                if not row or not row[0]:
                    continue
                classification = str(row[0]).strip()
                if "B2C" not in classification.upper():
                    continue
                sections = [str(c).strip() for c in row[1:5] if c]
                if len(sections) != 4:
                    continue
                frameworks.append({
                    "domain": domain_file,
                    "classification": classification,
                    "sections": dict(zip(CANONICAL_IDS, sections)),
                    "respondent_logic": str(row[5]).strip() if len(row) > 5 and row[5] else "",
                })
            break

        # --- Sheet 1: the sub-sector rows ---
        ws = wb[wb.sheetnames[0]]
        for i, row in enumerate(ws.iter_rows(values_only=True)):
            if i == 0 or not row or not row[0]:
                continue
            cls = str(row[3]).strip() if len(row) > 3 and row[3] else ""
            if "B2C" not in cls.upper():
                continue  # pure B2B sub-sectors are out of scope here
            attrs = {}
            # Columns run: cat1, attrs1, cat2, attrs2, cat3, attrs3, cat4, attrs4
            for n, col in enumerate(range(5, 13, 2)):
                if col < len(row):
                    attrs[CANONICAL_IDS[n]] = _split_attrs(row[col])
            subsectors.append({
                "domain": str(row[0]).strip(),
                "parent_market": str(row[1]).strip() if row[1] else "",
                "sub_sector": str(row[2]).strip(),
                "classification": cls,
                "attributes": attrs,
            })
        wb.close()

    return frameworks, subsectors


def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(2)

    frameworks, subsectors = build(sys.argv[1])
    print(f"frameworks: {len(frameworks)}   b2c sub-sectors: {len(subsectors)}")

    out = Path(__file__).resolve().parent.parent / "src" / "cmi_frameworks.py"
    header = '''"""CMI survey frameworks and B2C sub-sector taxonomy.

# change for b2c questionarie

GENERATED by scripts/build_cmi_frameworks.py from the CMI Domains workbooks —
do not hand-edit. Re-run the builder if the source workbooks change.

`B2C_FRAMEWORKS` gives the four survey categories a B2C study must use for a
given domain. They differ by domain: a food market opens on consumption
occasions, an electronics market on device ownership. All map onto the same
four canonical ids in arc order (usage -> purchase -> experience -> intent).

`B2C_SUBSECTORS` is the sub-sector taxonomy with the Top-5 attributes CMI
expects each category to cover, used as must-cover seed topics.
"""
from __future__ import annotations

CANONICAL_IDS = (
    "consumer_profile",
    "buying_behavior",
    "preferences_expectations",
    "satisfaction_future_intent",
)

'''
    body = (
        "B2C_FRAMEWORKS = "
        + pprint.pformat(frameworks, width=88, sort_dicts=False)
        + "\n\nB2C_SUBSECTORS = "
        + pprint.pformat(subsectors, width=88, sort_dicts=False)
        + "\n"
    )
    out.write_text(header + body, encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
